//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaires
    {
        public Commentaires()
        {
            this.Commentaires1 = new HashSet<Commentaires>();
        }
    
        public int IdCommentaire { get; set; }
        public string Titre { get; set; }
        public string Commentaire { get; set; }
        public System.DateTime DateCommentaire { get; set; }
        public int IdHotel { get; set; }
        public int IdUtilisateur { get; set; }
        public Nullable<int> IdCommentaireReference { get; set; }
    
        public virtual ICollection<Commentaires> Commentaires1 { get; set; }
        public virtual Commentaires Commentaires2 { get; set; }
        public virtual Hotels Hotels { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
